version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://Eya:root@cluster0.qnwwaqq.mongodb.net/
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
